# permissions for end users to view nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: nfs-viewer-role
rules:
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs/status
  verbs:
  - get
