# permissions for end users to edit nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-editor-role
rules:
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs/status
  verbs:
  - get
