# permissions for end users to edit nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfs-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: storage-operator
    app.kubernetes.io/part-of: storage-operator
    app.kubernetes.io/managed-by: kustomize
  name: nfs-editor-role
rules:
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.csas.cz
  resources:
  - nfs/status
  verbs:
  - get
