---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for manipulate from PersistentVolume, PersistentVolumeClaim and StorageClass
  ##
  - apiGroups:
      - ""
    #attributeRestrictions: null
    resources:
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    #attributeRestrictions: null
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - patch
      - watch
  ##
  ## Rules for storage.csas.cz/v1, Kind: Nfs
  ##
  - apiGroups:
      - storage.csas.cz
    resources:
      - nfs
      - nfs/status
      - nfs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
