---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nfs.storage.csas.cz
spec:
  group: storage.csas.cz
  names:
    kind: Nfs
    listKind: NfsList
    plural: nfs
    singular: nfs
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Nfs is the Schema for the nfs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Nfs
            properties:
              server:
                description: NFS server name
                type: string
              path:
                description: Export path
                type: string
            required:
            - server
            - path
            type: object
          status:
            description: Status defines the observed state of Nfs
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
